### ISSUE TITLE
Worthy Testing Framework - Mocking and stubbing

### ISSUE THREAD

**Issue by Tolvic** [PreetiSekhon2/NoteWorthy#10]
Unable to mock and stub. Please add in this functionality.

**Comment by aimeecraig** [comment]
Test comment

**Comment by aimeecraig** [comment]
Fuck you Terry!

**Comment by Tolvic** [comment]
....................../´¯/) 
....................,/¯../ 
.................../..../ 
............./´¯/'...'/´¯¯`?¸ 
........../'/.../..../......./¨¯ 
........('(...´...´.... ¯~/'...') 
.........\.................'...../ 
..........\...\.......... ....?´ 
............\..............( 
..............\.............\....

**Comment by aimeesophia** [comment]
Functionality added in latest pull request.
